### ISSUE TITLE
Radu ToDo List

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#10]
- [x] Fix build

- [x] Change title in link of 'Adaptable' page to 'AdapTable'

- [x] Remove contact link from footer

- [x] Change text in footer from 'Linkedin Page' to 'LinkedIn' (note the capital I) 

- [x] Implement the email box in footer

- [x] The Template for a new story / blog post currently has a bullet and then a date after the title. can we put the date on a line below the title (same font as currently) and then drop the bullet as wont be needed.

- [x] Drop the pictures in the Grid Gurus quotes - like with home page just have the quotes but without the pic.  Make them MarkDown (if not already) so easy to format.

- [x] Rename 'Other Data Tools' page to 'FinTech Partners' (Sorry!!!) 

- [x] General:  Update the stylesheet (?) used so that links become obvious - at the moment with black text you cannot see what is a link or not (e.g. Partners page)

- [x] General: Drop down main images on each page so they appear beneath the header - if possible! (a topmargin?) . I dont like how they fade at the top but in any case its worse in this case as our toolbar has to be visible :(

- [x] Header:  Shorten it - make the space between the 2 rows of links smaller and if need be shorten the logo (which will change today)

- [x] Footer: Change second paragraph to 'Adaptable Tools currently works with clients in Financial Services and other sectors from its London HQ.'

- [x] Footer: Put the 3 contact links (email/phone/linkedin) above the form on the right hand side and make the whole footer much shorter (i.e. reduce top and bottom margin)

- [x] Footer: Shrink the text for the email box (its huge when typed!) and put the 'Send' button to the right of the box

- [x] Landing Page: Add a 2nd Call to Action between Clients and Awards

- [x] Adaptable page: The Optional Description (which we have provided) is not appearing on the published page!

- [x] Adaptable page: Make the Optional Description markdown

- [x] Adaptable page: Centre justify title above the videos 'AdapTable's Unique offer'

- [x] Adaptable page: Put the descriptive text above each video.

- [x] Adaptable page: In the case studies change 'Adaptable' to 'AdapTable'

- [x] Adaptable page: Make the 'Try Adaptable for Yourself' Call to Action more obviously a button (as in landing page)

- [x] Grid Gurus: Add an image above each of the 4 items in 'Our Services' (similar to how it is done in Home page) - i have them as svg

- [x] Partners Page: Add an image section below the text for each partner - the image should go across the whole page

- [x] News: Change the 'banner tag' to 'Latest updates from Adaptable Tools'

- [x] News: dont have access to it in Content Manager - need to update image (or can send to you)
