### ISSUE TITLE
Danielle ToDo List

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [AdaptableTools/ab-website#9]
- [x] latest story needs a second 'T' in Blotter (currently says 'Bloter')

- [x] Add a wosna story

- [x] Source a partner image for the Partner image
